### ISSUE TITLE
Failed to detect Archicad version, please check the value of the  AC_API_DEVKIT_DIR variable

### ISSUE THREAD

**Issue by mcbabo** [GRAPHISOFT/archicad-addon-cmake#12]
I tried to follow the steps from here [https://archicadapi.graphisoft.com/getting-started-with-archicad-add-ons](https://archicadapi.graphisoft.com/getting-started-with-archicad-add-ons), but I get an error when I try to run this command.

```cmake
cmake -G "Visual Studio 17 2022" -A "x64" -DAC_API_DEVKIT_DIR="C:\Program Files\GRAPHISOFT\API Development Kit 26.3000" ..
```

```
CMake Error at CMakeLists.txt:59 (message):
  Failed to detect Archicad version, please check the value of the
  AC_API_DEVKIT_DIR variable.
-- Configuring incomplete, errors occurred!
```

I have installed the API Dev Kit 26.3000 under the provided Path.

**Comment by kovacsv** [comment]
For some reason the behaviour changed, now you need to provide the location of the `Support` folder in the DevKit. Try this command:
```
cmake -G "Visual Studio 17 2022" -A "x64" -DAC_API_DEVKIT_DIR="C:\Program Files\GRAPHISOFT\API Development Kit 26.3000\Support" ..
```

**Comment by mcbabo** [comment]
Ja hat geklappt danke, wenn ich jetzt in VS bei "AddOn" auf Erstellen drücke kommen zwei Fehler:
```
MSB8066	Der benutzerdefinierte Build für "\archicad-addon-cmake-master\Build\CMakeFiles\535d4c75405f7e7aee7efaa87e2a7a3c\AddOnResources.stamp.rule; 
archicad-addon-cmake-master\Build\CMakeFiles\993873dc381d848f5c59f37ad491ceaf\AddOnResources.rule" wurde mit dem Code 1 beendet.
```

```
LNK1104	Datei "archicad-addon-cmake-master\Build\ResourceObjects\ExampleAddOn.res" kann nicht geöffnet werden.
```

Anscheinend wurde die .res Datei nicht automatisch generiert

**Comment by mcbabo** [comment]
Yes, it worked, thanks, when I press create in VS for "AddOn" I get two errors:
```
MSB8066	Custom build for \archicad-addon-cmake-master\Build\CMakeFiles\535d4c75405f7e7aee7efaa87e2a7a3c\AddOnResources.stamp.rule;
\archicad-addon-cmake-master\Build\CMakeFiles\993873dc381d848f5c59f37ad491ceaf\AddOnResources.rule' exited with code 1.
```
```
LNK1104	cannot open file '\archicad-addon-cmake-master\Build\ResourceObjects\ExampleAddOn.res'
```

**Comment by kovacsv** [comment]
Are you sure you have python installed on your computer?

**Comment by mcbabo** [comment]
Yes, 
I solved the problem by using v142 and not v143

**Comment by RDelen** [comment]
> Are you sure you have python installed on your computer?

Hello, I'm new here. Does this mean inside the visual studio or really python software in the computer?
